# -*- coding: utf-8 -*-
"""
游戏常量定义
"""

# 方向常量
DIRECTION_UP = 0
DIRECTION_DOWN = 1
DIRECTION_LEFT = 2
DIRECTION_RIGHT = 3

DIRECTION_VECTORS = {
    DIRECTION_UP: (0, -1),
    DIRECTION_DOWN: (0, 1),
    DIRECTION_LEFT: (-1, 0),
    DIRECTION_RIGHT: (1, 0),
}

# 游戏状态
STATE_PLAYING = 0
STATE_PAUSED = 1
STATE_DIALOGUE = 2
STATE_BATTLE = 3
STATE_MENU = 4

# 瓦片类型
TILE_EMPTY = 0
TILE_GRASS = 1
TILE_DIRT = 2
TILE_WATER = 3
TILE_WALL = 4
TILE_DOOR = 5

# 碰撞瓦片列表
COLLISION_TILES = [TILE_WATER, TILE_WALL]

# 物品类型
ITEM_TYPE_WEAPON = "weapon"
ITEM_TYPE_ARMOR = "armor"
ITEM_TYPE_CONSUMABLE = "consumable"
ITEM_TYPE_KEY = "key"
ITEM_TYPE_MISC = "misc"

# 战斗相关
BATTLE_ACTION_ATTACK = 0
BATTLE_ACTION_SKILL = 1
BATTLE_ACTION_ITEM = 2
BATTLE_ACTION_DEFEND = 3
BATTLE_ACTION_ESCAPE = 4

# 动画相关
ANIM_SPEED_SLOW = 15
ANIM_SPEED_NORMAL = 10
ANIM_SPEED_FAST = 5
